name: Post to X

on:
  push:
    branches:
      - main
    paths:
      - 'content/**'
  schedule:
    # UTC 08:00 → JST 17:00
    # UTC 20:00 → JST 05:00
    - cron: '0 8,20 * * *'

jobs:
  # ────────────────
  immediate_post:  # プッシュイベント時のみ実行
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Ensure tooling (jq)
        run: |
          sudo apt-get update -y
          sudo apt-get install -y jq

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tweepy

      - name: Gather changed files
        id: changed
        run: |
          # null 安全にコミット差分を取得
          FILES=$(jq -r '.commits // [] | .[].added[], .[].modified[]' < "$GITHUB_EVENT_PATH" | tr '\n' ' ')
          echo "list=$FILES" >> "$GITHUB_OUTPUT"

      - name: Pick last non-datetime media (.mp4)
        id: pick
        run: |
          FILES="${{ steps.changed.outputs.list }}"
          LAST=""
          for f in $FILES; do
            # 対象: content/ 内の .mp4 のみ
            case "$f" in
              content/*.mp4)
                base=$(basename "$f")
                if echo "$base" | grep -Eq '^[0-9]{10}\.mp4$'; then
                  continue
                fi
                LAST="$f"
                ;;
            esac
          done
          echo "last=$LAST" >> "$GITHUB_OUTPUT"

      - name: Post last file (auto-read matching .txt)
        if: ${{ steps.pick.outputs.last != '' }}
        env:
          X_API_KEY:             ${{ secrets.X_API_KEY }}
          X_API_SECRET_KEY:      ${{ secrets.X_API_SECRET_KEY }}
          X_ACCESS_TOKEN:        ${{ secrets.X_ACCESS_TOKEN }}
          X_ACCESS_TOKEN_SECRET: ${{ secrets.X_ACCESS_TOKEN_SECRET }}
        run: |
          if [ -z "$X_API_KEY" ] || [ -z "$X_API_SECRET_KEY" ] || [ -z "$X_ACCESS_TOKEN" ] || [ -z "$X_ACCESS_TOKEN_SECRET" ]; then
            echo "Required X API secrets are not set. Skipping post." >&2
            exit 1
          fi
          FILE="${{ steps.pick.outputs.last }}"
          python post_to_x.py --file "$FILE"

  # ────────────────
  scheduled_post:  # 予約投稿（スケジュール）時のみ実行
    if: ${{ github.event_name == 'schedule' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tweepy

      - name: Post scheduled datetime files
        env:
          X_API_KEY:             ${{ secrets.X_API_KEY }}
          X_API_SECRET_KEY:      ${{ secrets.X_API_SECRET_KEY }}
          X_ACCESS_TOKEN:        ${{ secrets.X_ACCESS_TOKEN }}
          X_ACCESS_TOKEN_SECRET: ${{ secrets.X_ACCESS_TOKEN_SECRET }}
        run: |
          # JST でファイル名を生成
          NOW=$(TZ=Asia/Tokyo date +%Y%m%d%H)
          VIDEO="content/${NOW}.mp4"
          TEXT="content/${NOW}.txt"

          if [ -z "$X_API_KEY" ] || [ -z "$X_API_SECRET_KEY" ] || [ -z "$X_ACCESS_TOKEN" ] || [ -z "$X_ACCESS_TOKEN_SECRET" ]; then
            echo "Required X API secrets are not set. Skipping post." >&2
            exit 1
          fi

          if [ -f "$VIDEO" ] && [ -f "$TEXT" ]; then
            python post_to_x.py --video "$VIDEO" --text "$TEXT"
          else
            echo "No scheduled files for ${NOW}"
          fi
